name: Build Linux

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake pkg-config libgtk-3-dev libayatana-appindicator3-dev wl-clipboard g++ zip libzstd-dev

      - name: Configure & Build
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build -j$(nproc)

      - name: Package Binary
        run: |
          VERSION=${{ github.ref_name }}
          EXPORT_NAME="copas-linux-${VERSION}"

          mkdir -p "dist/${EXPORT_NAME}"
          cp build/copas "dist/${EXPORT_NAME}/"
          [ -f README.md ] && cp README.md "dist/${EXPORT_NAME}/"

          cd dist
          zip -r "${EXPORT_NAME}.zip" "${EXPORT_NAME}"

      - name: Upload Binary to release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/copas-linux-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
